#.
#URL to send data to.
"Metrics Endpoint URL" = "https://analyticsinjest.txni.dev/"
#.
#Identifier for this modpack
"Pack ID" = "mmc5neoforge"
#.
#Interval between keepalive requests, in minutes.
# Default: 30
# Range: > -2147483648
"Update Rate" = 30
